### ISSUE TITLE
NPE in ConsoleDriver

### ISSUE THREAD

**Issue by AmandaCameron** [gamax92/Thistle#1]
Just re-posting this here for ya:
```
java.lang.NullPointerException
	at gamax92.thistle.util.ConsoleDriver.flush(ConsoleDriver.java:381)
	at gamax92.thistle.devices.ThistleIO.flush(ThistleIO.java:214)
	at gamax92.thistle.ThistleVM.run(ThistleVM.java:38)
	at gamax92.thistle.ThistleArchitecture.runThreaded(ThistleArchitecture.java:121)
	at li.cil.oc.server.machine.Machine.run(Machine.scala:948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Possibly being caused by me using DMA incorrectly, but I'm pretty dead myself atm, so I'll investigate tomorrow.

**Comment by gamax92** [comment]
Likely fixed by 67a6c07a2cb36fc7248fafa96949fc248c72de7e
