### ISSUE TITLE
Computer crashes when pasting a lot of text (MC 1.12.2, using https://github.com/thePalindrome/Thistle/releases/tag/1.1.0-1.12 + new boot ROM)

### ISSUE THREAD

**Issue by 20kdc** [gamax92/Thistle#8]
The exception:
```
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: java.lang.IndexOutOfBoundsException
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.common.component.TextBuffer.color(TextBuffer.scala:447)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.common.component.TextBuffer.isForegroundFromPalette(TextBuffer.scala:396)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.common.component.TextBuffer.getForegroundColor(TextBuffer.scala:388)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.component.GraphicsCard$$anonfun$get$1.apply(GraphicsCard.scala:255)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.component.GraphicsCard$$anonfun$get$1.apply(GraphicsCard.scala:254)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.component.GraphicsCard.screen(GraphicsCard.scala:52)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.component.GraphicsCard.get(GraphicsCard.scala:254)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at generated.li.cil.oc.CallWrapper_li_cil_oc_server_component_GraphicsCard_get.call(Unknown Source)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.network.Component$class.invoke(Component.scala:112)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:636)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:380)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at gamax92.thistle.util.ConsoleDriver.flush(ConsoleDriver.java:416)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at gamax92.thistle.devices.GeneralIO.flush(GeneralIO.java:214)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at gamax92.thistle.ThistleVM.run(ThistleVM.java:39)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at gamax92.thistle.ThistleArchitecture.runThreaded(ThistleArchitecture.java:126)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at li.cil.oc.server.machine.Machine.run(Machine.scala:992)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:08:23] [OpenComputers-Computer-4/INFO] [STDERR]: [gamax92.thistle.ThistleArchitecture:runThreaded:139]: 	at java.lang.Thread.run(Thread.java:748)
```
occurs when performing the following:
1. Make a new computer with the new boot EEPROM already present (I've swapped it in the JAR I'm using). I used a Tier 3 APU (i.e. Tier 2 graphics) connected to a Tier 3 screen. If exact details are required, comment.
2. Paste (using the middle mouse button) the following:

```
LDA #$F0
STA $01
STZ $00
LDA $E000
BEQ 0xFB
LDA $E001
BNE 0X05
LDA $E001
BRA 0xF1
STA $E003
CMP #' '
BCC 0xEA
CMP #';'
BEQ 0xE0
ASL
ASL
ASL
ASL
STA ($00)
LDA $E001
STA $E003
AND #$0F
EOR ($00)
STA ($00)
INC $00
BNE 0xD0
INC $01
BRA 0xCC
```

3. Run the program using "run" followed by a newline.
4. Paste `BMBMEKEKDCDADBDECJEDFHFIGCGDFLFECJDHEJJJDJDJDJDJJHKILIOIHM@CN@HJBI@OJHKILIOIHM@CN@GJFHF@JI@MHM@CN@JI@JHM@CN@F@J@@@KAHEB@AAO@LHL@A@O@AIL@@DO@@NL@@FO@@JL@@HO@@FL@@JO@@BH@NDJIBMHM@CN@H@MMDLBLO@JM` repeatedly until the computer crashes.
(The quoted text is the first part of the boot ROM encoded in the lower 4 bits. The program is an EEPROM flasher.)

**Comment by 20kdc** [comment]
OpenComputers version being used is `OpenComputers-MC1.12.2-1.7.5.192`.

**Comment by 20kdc** [comment]
So I think I found one possible cause: the `Y` value can temporarily go out of bounds.
https://github.com/gamax92/Thistle/blob/master/src/main/java/gamax92/thistle/util/ConsoleDriver.java#L165 is *supposed* to resolve this but defers it, which means if too much happens "at once" then the cursor goes further out of bounds...
